In [3]:
from transformers import DistilBertModel,DistilBertTokenizer
import transformers as ppb # pytorch transformers
import re

import nltk
from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("english")
import re
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jafar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [4]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('bert-base-nli-mean-tokens')


In [5]:
def cleaning (text):
    
    emoji_pattern = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                               u"\U00002702-\U000027B0"
                               u"\U000024C2-\U0001F251"
                               u"\U0001f926-\U0001f937"
                               u"\u2640-\u2642"
                               u"\u2600-\u2B55"
                               u"\u23cf"
                               u"\u23e9"
                               u"\u231a"
                               u"\u3030"
                               "]+", flags=re.UNICODE)
    #removing emoji
    text = emoji_pattern.sub(r' ', text)   

    #removeing http and https (URL)
    text = re.sub(r'(http://|https://)\S+', '', text)
    
    #removing www (URL)
    text=re.sub(r'www\.\S+', '', text)
    
    #removing targets
    text=re.sub('( |^)@\S+', '', text) 
    
    #removing tabs and lines
    text=re.sub('\t|\n', '', text)

    #removing some special charachter  
    text= re.sub("[\"\“\”\+\-\|\*\?\(\)\/\\\^\[\]\.{}_`;,@:~!=%&'’]+", ' ',text) 
    
    #removing hashtag
    text=re.sub('#', '', text) 
    
    #removing numbers
    text=re.sub("(\d+)",' ',text)
    
    #removing numbers (not attached)
#    text=re.sub(r"(^|\s)-?(\d+)\.?(\d*)(\s)", '', text)
#    text=re.sub("(^||\d+)\.(\d+) ",'',text)
#    text=re.sub("[0-9+]\.?(\d+)(\.)",' ',text)
#    text=re.sub("[0-9+]\.?(\d+)($)",' ',text)
#    print(text)
    
#    return text

#def lower_case (text):
#    text = text.lower() 
#    return text_lower

#def tokenization (text):
#    text= nltk.word_tokenize(text)
#    print (text)
#    return text_tokens

#def removing_stopwords (text):
    #text_without_sw = [word.lower() for word in text if word.lower() not in stopwords.words()]
#    text = [word for word in text if word not in stopwords.words()]
#    print(text)
#    return text_without_sw

#def stemming (text):
    #stemmer = SnowballStemmer("english")
    #text_stems=stemmer.stem(tokens_without_sw)
#    text = [stemmer.stem(word) for word in text]
#    print(text)
    
#    text=' '.join(text)
#    print(text,'\n')   
    
    return text


In [6]:
sentences = ['There is framework generates embeddings for each input sentence',
            'Sentences are passed as a list of string.', 
            'The quick brown wolf  jumps over the lazy dog.',
            'I like lion alot I admire it ',
            'many people love lion ',
            'lion is powerful',
            'lions are powerful',
            'I LOVE LION',
            'There ’s framework generates embeddings for each input sentence']
sentence_embeddings = model.encode(sentences)

In [7]:
print(len(sentence_embeddings))
print(len(sentence_embeddings[0]))

9
768


In [8]:
emed_ind=[]
for sen in sentences:
    emed_ind.append(model.encode(sen))

In [9]:
print(len(emed_ind))
print(len(emed_ind[0][0]))

9
768


In [10]:
#emed_ind[0][0]==sentence_embeddings[0] #false

In [11]:
'''
for sentence, embedding in zip(sentences, sentence_embeddings):
    print("Sentence:", sentence)
 #   print("Embedding:", embedding)
    print("")
'''    

'\nfor sentence, embedding in zip(sentences, sentence_embeddings):\n    print("Sentence:", sentence)\n #   print("Embedding:", embedding)\n    print("")\n'

In [12]:
from scipy.spatial.distance import cosine

diff = 1 - cosine(sentence_embeddings[5], sentence_embeddings[6])
print(diff)
same = 1 - cosine(sentence_embeddings[4], sentence_embeddings[3])
print(same)

same2 = 1 - cosine(sentence_embeddings[3], sentence_embeddings[7])
print(same2)

same3 = 1 - cosine(sentence_embeddings[0], sentence_embeddings[8])
print(same3)

0.9629046320915222
0.8583279848098755
0.9233848452568054
0.9927574992179871


In [13]:
'''
sentences1=[]
for sen in sentences:
    sentences1.append(cleaning(sen))
sentences1[0]
'''

'''
sentence_embeddings = model.encode(sentences1)
for sentence, embedding in zip(sentences1, sentence_embeddings):
    print("Sentence:", sentence)
 #   print("Embedding:", embedding)
    print("")
'''    

'''
from scipy.spatial.distance import cosine

diff = 1 - cosine(sentence_embeddings[5], sentence_embeddings[6])
print(diff)
same = 1 - cosine(sentence_embeddings[4], sentence_embeddings[3])
print(same)

same2 = 1 - cosine(sentence_embeddings[3], sentence_embeddings[7])
print(same2)

same3 = 1 - cosine(sentence_embeddings[0], sentence_embeddings[8])
print(same3)
'''

'\nfrom scipy.spatial.distance import cosine\n\ndiff = 1 - cosine(sentence_embeddings[5], sentence_embeddings[6])\nprint(diff)\nsame = 1 - cosine(sentence_embeddings[4], sentence_embeddings[3])\nprint(same)\n\nsame2 = 1 - cosine(sentence_embeddings[3], sentence_embeddings[7])\nprint(same2)\n\nsame3 = 1 - cosine(sentence_embeddings[0], sentence_embeddings[8])\nprint(same3)\n'

In [14]:
sentenc1 = ['There is framework generates embeddings for each input sentence',
    'Sentences are passed as a list of string.', 
    'The quick brown wolf  jumps over the lazy dog.',
            'I like lion alot I admire it ',
            'many people love lion ',
            'lion is powerful']
sentenc2 = ['lions are powerful',
            'I LOVE LION',
            'There ’s framework generates embeddings for each input sentence']
sentence_embedding1 = model.encode(sentenc1)
sentence_embedding2 = model.encode(sentenc2)

In [15]:
from scipy.spatial.distance import cosine

diff = 1 - cosine(sentence_embedding1[5], sentence_embedding2[0])
print(diff)
same = 1 - cosine(sentence_embedding1[4], sentence_embedding1[3])
print(same)

same2 = 1 - cosine(sentence_embedding1[3], sentence_embedding2[1])
print(same2)

same3 = 1 - cosine(sentence_embedding1[0], sentence_embedding2[2])
print(same3)

0.9629046320915222
0.8583279848098755
0.9233848452568054
0.9927574992179871


In [16]:
print(len(sentence_embedding2))
print(len(sentence_embedding2[0]))

3
768


In [17]:
#sentence_embedding2[0]==sentence_embeddings[6] # false

In [18]:
sentences = ['There is framework generates embeddings for each input sentence',
    'Sentences are passed as a list of string.', 
    'The quick brown wolf  jumps over the lazy  dog.',
            'I like lion alot I admire it ',
            'many people love lion ',
            'lion is powerful',
            'lions are powerful',
            'I LOVE LION',
            'There ’s framework generates embeddings for each input sentence',
            'I   LOVE         LION     ',
            '',
            'There ’ s framework generates embeddings for each input sentence']
sentence_embed=[]
for sentence in sentences:
    sentence_embed.append(model.encode(sentence))

In [19]:
from scipy.spatial.distance import cosine

diff = 1 - cosine(sentence_embed[5], sentence_embed[6])
print(diff)
same = 1 - cosine(sentence_embed[4], sentence_embed[3])
print(same)

same2 = 1 - cosine(sentence_embed[3], sentence_embed[7])
print(same2)

same3 = 1 - cosine(sentence_embed[0], sentence_embed[8])
print(same3)

same4 = 1 - cosine(sentence_embed[9], sentence_embed[7])
print(same4)

same5 = 1 - cosine(sentence_embed[9], sentence_embed[10])
print(same5)

1 - cosine(sentence_embed[8], sentence_embed[11])

0.9629045724868774
0.8583279252052307
0.9233848452568054
0.9927576780319214
1.0
0.25023797154426575


1.0

In [20]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('bert-base-nli-mean-tokens')

In [21]:
sentences = ['There is framework generates embeddings for each input sentence',
            'Sentences are passed as a list of string.', 
            'The quick brown wolf  jumps over the lazy  dog.',
            'I like lion alot I admire it ',
            'many people love lion ',
            'lion is powerful',
            'lions are powerful',
            'I LOVE LION',
            'There ’s framework generates embeddings for each input sentence',
#            'the see is blue'
            ]

In [22]:
sen_embedding = model.encode(sentences)

In [23]:
lion_embedding = model.encode("sentence")

In [24]:
from scipy.spatial.distance import cosine
sim=[]
for sen in sen_embedding:
     ans= 1 - cosine(sen, lion_embedding)
     sim.append(ans)
sim   

[0.5269836187362671,
 0.6499285101890564,
 -0.1370430886745453,
 0.1616545170545578,
 0.04988108202815056,
 0.19501909613609314,
 0.16941632330417633,
 0.17842039465904236,
 0.5310317873954773]

In [25]:
from sklearn.cluster import OPTICS
import time 

t0 = time.time()
clustering = OPTICS(min_samples=2).fit(sen_embedding)
print(clustering.labels_)
print( time.time() - t0)
print(clustering.reachability_)
print(clustering.ordering_)
print(clustering.core_distances_)
print(clustering.predecessor_)
print(clustering.cluster_hierarchy_)

[0 0 2 1 1 2 2 1 0]
0.007979869842529297
[        inf 10.86120027 19.27667554 21.53402804  8.77033528 11.91414628
  4.6796679   6.64826383  1.93722667]
[0 8 1 3 7 4 5 6 2]
[ 1.93722667 10.86120027 19.27667554  6.64826383  8.77033528  4.6796679
  4.6796679   6.64826383  1.93722667]
[-1  8  6  8  7  7  5  3  0]
[[0 2]
 [3 5]
 [6 8]
 [3 8]
 [0 8]]


In [42]:
["foo", "bar", "baz"].index("bar")
xs=["foo", "bar", "baz"]
#[i for i, j in enumerate(['foo', 'bar', 'baz']) if j == 'bar']
for i, j in enumerate(['foo', 'bar', 'baz']):
    if j == 'bar':
        print(i,j)


1 bar


In [43]:
import numpy as np
aa=clustering.labels_

bb=np.where(aa==0)
list(bb[0])

[0, 1, 8]

In [44]:
#help(["foo", "bar", "baz"])

In [28]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3)
t0 = time.time()
clustering = kmeans.fit(sen_embedding)
print( time.time() - t0)
clustering.labels_

0.02792525291442871


array([0, 0, 2, 1, 1, 1, 1, 1, 0])

In [56]:
clustering.cluster_centers_

array([[-0.02599126,  0.13011003,  1.20615665, ..., -0.29086496,
        -0.41890414,  0.64663762],
       [ 0.22536715,  0.41066814,  0.1160614 , ..., -0.12130176,
        -0.11097692, -0.38311562],
       [-0.7870037 ,  0.7854169 , -1.81107652, ..., -0.12256152,
         1.11515939, -0.1423967 ]])

In [57]:
clustering.inertia_

323.74769768403075

In [34]:
from sklearn.mixture import GaussianMixture as GMM
gmm = GMM(n_components=3).fit(sen_embedding)
labels = gmm.predict(sen_embedding)
print(labels.round(3))

[0 0 2 1 1 1 1 1 0]
